dataset_name: cataracts50
class_size: 18
ignore_index: last # only first or last
data_root: /path/to/dataset/Cataracts-50
log_dir: ./checkpoints/Cataracts-50
num_graph_in_3d: 16
overlap_size: 4 # 1 for max overlap; num_graph_in_3d for no overlap 

size: 128
batch_size: 2
num_workers: 16
weight_decay: 1e-5
patience: 1
factor: 0.8
epochs: 200
device: cuda

graph_encoder_lr: 1e-4 # 5e-5 for segclip
graph_input_dim: 25 # class_size + 2 + 2 + 3
graph_hidden_dim: 256
graph_embedding_dim: 256
graph_conv_type: GATv2Conv # GCNConv or GATConv or GATv2Conv or TransformerConv or SAGEConv or ChebConv or GINConv
graph_norm_type: LayerNorm # BatchNorm or GraphNorm or LayerNorm or InstanceNorm

image_encoder_lr: 5e-6
image_embedding_dim: 256
image_encoder_config: ./checkpoints/Cataracts-50/vqgan_image/config.yaml
image_encoder_ckpt: ./checkpoints/Cataracts-50/vqgan_image/checkpoint.ckpt

segmentation_encoder_lr: 1e-7 # not being used
segmentation_embedding_dim: 256
segmentation_encoder_config: ./checkpoints/Cataracts-50/vqgan_segmentation/config.yaml
segmentation_encoder_ckpt: ./checkpoints/Cataracts-50/vqgan_segmentation/checkpoint.ckpt

trainable: True
temperature: 1.0
dropout: 0.2